apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2atmmovil
  labels:
    assign-to: "data-stor"
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 169.48.64.250
    path: /storage/db2vol-atmmovil