

--DROP TABLE "APP_CONFIG";
CREATE TABLE "APP_CONFIG" (
  "APP_CONFIG_ID" DECIMAL NOT NULL ,
  "KEY" VARCHAR(128) ,
  "AU_USUARIO_CREACION" VARCHAR(64) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(64) ,
  "AU_FECHA_MOD" TIMESTAMP ,
  "ELIMINADO" DECIMAL ,
  "VALUE" CLOB (10K)
);

--DROP TABLE "CAT_ESTATUS";
CREATE TABLE "CAT_ESTATUS" (
  "CAT_ESTATUS_ID" DECIMAL NOT NULL ,
  "NOMBRE" VARCHAR(64) ,
  "ALIAS" VARCHAR(64)
);

--DROP TABLE "CAT_ESTATUS_DESCRIPCION";
CREATE TABLE "CAT_ESTATUS_DESCRIPCION" (
  "ESTATUS_DESC_ID" DECIMAL NOT NULL ,
  "ESTATUS_SIS_ID" VARCHAR(25) NOT NULL ,
  "CAT_ESTATUS_ID" DECIMAL NOT NULL ,
  "DESC_SISTEM" VARCHAR(25)
);

--DROP TABLE "CAT_INCIDENCIA";
CREATE TABLE "CAT_INCIDENCIA" (
  "CAT_INCIDENCIA_ID" DECIMAL NOT NULL ,
  "NOMBRE" VARCHAR(80) NOT NULL ,
  "PADRE_ID" DECIMAL ,
  "IMAGEN_URL" VARCHAR(128) ,
  "AU_USUARIO_CREACION" VARCHAR(64) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(64) ,
  "AU_FECHA_MOD" TIMESTAMP ,
  "ELIMINADO" DECIMAL ,
  "TIPO_UNIDAD_ID" DECIMAL ,
  "EXT_APP" VARCHAR(20) ,
  "NIV_SERV_DIAS" DECIMAL ,
  "PREAUT_ROL_ID" DECIMAL ,
  "PREAUT_REQ" DECIMAL ,
  "FE_UPDATE" DECIMAL ,
  "ID_OTHER_SYSTEM" DECIMAL ,
  "COMENTARIO_SYS_INCIDENCIA" VARCHAR(100) ,
  "SYS_INCIDENCIA" VARCHAR(60) ,
  "NOTIFICA_INCIDENCIA" DECIMAL
);

--DROP TABLE "CAT_INCIDENCIA_DET";
CREATE TABLE "CAT_INCIDENCIA_DET" (
  "CAT_INCIDENCIA_DET_ID" DECIMAL NOT NULL ,
  "CAT_INCIDENCIA_ID" DECIMAL NOT NULL ,
  "NOMBRE" VARCHAR(150) NOT NULL ,
  "TIPO_PREGUNTA" DECIMAL NOT NULL ,
  "AU_USUARIO_CREACION" VARCHAR(64) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(64) ,
  "AU_FECHA_MOD" TIMESTAMP ,
  "ELIMINADO" DECIMAL
);

--DROP TABLE "CAT_INCIDENCIA_EMAIL";
CREATE TABLE "CAT_INCIDENCIA_EMAIL" (
  "CAT_INCIDENCIA_EMAIL_ID" DECIMAL NOT NULL ,
  "CAT_INCIDENCIA_ID" DECIMAL ,
  "EMAIL" VARCHAR(128) ,
  "AU_USUARIO_CREACION" VARCHAR(64) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(64) ,
  "AU_FECHA_MOD" TIMESTAMP ,
  "ELIMINADO" DECIMAL ,
  "ESTATUS" DECIMAL
);

--DROP TABLE "CAT_INCIDENCIA_ROL";
CREATE TABLE "CAT_INCIDENCIA_ROL" (
  "CAT_INCIDENCIA_ROL_ID" DECIMAL NOT NULL ,
  "CAT_INCIDENCIA_ID" DECIMAL ,
  "ROL_ID" DECIMAL
);

--DROP TABLE "MOVIMIENTOS_TICKET_WS";
CREATE TABLE "MOVIMIENTOS_TICKET_WS" (
  "CAT_MOVIMIENTOS_TICKET_ID" DECIMAL NOT NULL ,
  "TICKET_ID" DECIMAL NOT NULL ,
  "WS_ATM_OBESERVACIONES" VARCHAR(500) ,
  "ESTATUS_ACTUAL" DECIMAL ,
  "AU_FECHA_MOVIMIENTO" TIMESTAMP ,
  "ESTATUS_ANTERIOR" DECIMAL
);

--DROP TABLE "MOVIMIENTOS_WS";
CREATE TABLE "MOVIMIENTOS_WS" (
  "CAT_MOVIMIENTOS_ID" DECIMAL NOT NULL ,
  "WS_REQUEST" VARCHAR(1000) ,
  "FECHA_WS_REQUEST" TIMESTAMP ,
  "WS_RESPONSE" VARCHAR(1000) ,
  "FECHA_WS_RESPONSE" TIMESTAMP ,
  "MOVIMIENTO_DETALLE" VARCHAR(50)
);

--DROP TABLE "ROLES";
CREATE TABLE "ROLES" (
  "ROL_ID" DECIMAL NOT NULL ,
  "NOMBRE" VARCHAR(64) ,
  "DESCRIPCION" VARCHAR(512) ,
  "PERFIL" VARCHAR(20)
);

--DROP TABLE "TEMPORAL_USUARIOS";
CREATE TABLE "TEMPORAL_USUARIOS" (
  "TEMPORAL_USUARIOS_ID" DECIMAL NOT NULL ,
  "EMPLEADO" VARCHAR(30) ,
  "ROL" VARCHAR(45) ,
  "PERFIL" VARCHAR(45) ,
  "NOMBRE" VARCHAR(45) ,
  "APELLIDO" VARCHAR(45) ,
  "CORREO" VARCHAR(45) ,
  "ESTATUS" VARCHAR(45) ,
  "RESULTADO" VARCHAR(45) ,
  "TEMPORAL_FECHA_CREACION" TIMESTAMP
);

--DROP TABLE "TICKET";
CREATE TABLE "TICKET" (
  "TICKET_ID" DECIMAL NOT NULL ,
  "CAT_INCIDENCIA_ID" DECIMAL NOT NULL ,
  "UNIDAD_CODIGO" VARCHAR(20) NOT NULL ,
  "DESCRIPCION" VARCHAR(512) ,
  "CAT_ESTATUS_ID" DECIMAL DEFAULT 1 ,
  "FECHA" TIMESTAMP ,
  "USUARIO_ID" VARCHAR(20) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_CREACION" VARCHAR(20) ,
  "AU_FECHA_MOD" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(20) ,
  "EXT_APP_SYNC_ID" VARCHAR(20) ,
  "TICKET_ID_REL" DECIMAL ,
  "AU_FECHA_FINAL" TIMESTAMP
);

--DROP TABLE "TICKET_DET";
CREATE TABLE "TICKET_DET" (
  "TICKET_DET_ID" DECIMAL NOT NULL ,
  "TICKET_ID" DECIMAL NOT NULL ,
  "CAT_INCIDENCIA_DET_ID" DECIMAL NOT NULL ,
  "VALOR" VARCHAR(512) NOT NULL
);

--DROP TABLE "TICKET_IMG";
CREATE TABLE "TICKET_IMG" (
  "TICKET_IMG_ID" DECIMAL NOT NULL ,
  "TICKET_ID" DECIMAL NOT NULL ,
  "ARCHIVO" VARCHAR(512) NOT NULL ,
  "IMG_SISTEMA_EXTERNO" VARCHAR(20)
);

--DROP TABLE "TICKET_MSG";
CREATE TABLE "TICKET_MSG" (
  "TICKET_MSG_ID" DECIMAL NOT NULL ,
  "FECHA" TIMESTAMP NOT NULL ,
  "MENSAJE" VARCHAR(1024) NOT NULL ,
  "USUARIO" VARCHAR(64) NOT NULL ,
  "TICKET_ID" DECIMAL NOT NULL
);

--DROP TABLE "TIPO_UNIDAD";
CREATE TABLE "TIPO_UNIDAD" (
  "TIPO_UNIDAD_ID" DECIMAL NOT NULL ,
  "NOMBRE" VARCHAR(64) ,
  "AU_USUARIO_CREACION" VARCHAR(64) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(64) ,
  "AU_FECHA_MOD" TIMESTAMP
);

--DROP TABLE "TIPO_UNIDAD_ROL";
CREATE TABLE "TIPO_UNIDAD_ROL" (
  "TIPO_UNIDAD_ROL_ID" DECIMAL NOT NULL ,
  "TIPO_UNIDAD_ID" DECIMAL ,
  "ROL_ID" DECIMAL
);

--DROP TABLE "UNIDAD";
CREATE TABLE "UNIDAD" (
  "CODIGO" VARCHAR(30) NOT NULL ,
  "NOMBRE" VARCHAR(255) ,
  "DOMICILIO" VARCHAR(255) ,
  "COLONIA" VARCHAR(255) ,
  "ESTADO" VARCHAR(255) ,
  "CP" DECIMAL ,
  "VENTA_DLLS" DECIMAL ,
  "LATITUD" FLOAT ,
  "LONGITUD" FLOAT ,
  "AUTOBANCO" DECIMAL ,
  "PRIVADO" DECIMAL ,
  "ES_IXE" DECIMAL ,
  "ATM_MULTIPLE" DECIMAL ,
  "TIPO_UNIDAD_ID" VARCHAR(20) ,
  "CIUDAD" VARCHAR(255) ,
  "AU_USUARIO_CREACION" VARCHAR(64) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(64) ,
  "AU_FECHA_MOD" TIMESTAMP ,
  "ELIMINADO" DECIMAL ,
  "CR" VARCHAR(20) ,
  "TIPO_SERVICIO" VARCHAR(40) ,
  "ALIAS" VARCHAR(20) ,
  "TERRITORIO" VARCHAR(255) ,
  "REGIONAL" VARCHAR(35) ,
  "ETV" VARCHAR(10)
);

--DROP TABLE "USUARIO";
CREATE TABLE "USUARIO" (
  "USUARIO_ID" DECIMAL NOT NULL ,
  "NUMERO_USUARIO" VARCHAR(20) NOT NULL ,
  "NOMBRE" VARCHAR(50) ,
  "APELLIDO" VARCHAR(50) ,
  "ROL_ID" DECIMAL NOT NULL ,
  "PERFIL" VARCHAR(20) NOT NULL ,
  "CORREO" VARCHAR(50) ,
  "CODIGO" VARCHAR(50) ,
  "ELIMINADO" DECIMAL NOT NULL ,
  "AU_USUARIO_CREACION" VARCHAR(20) ,
  "AU_FECHA_CREACION" TIMESTAMP ,
  "AU_USUARIO_MOD" VARCHAR(20) ,
  "AU_FECHA_MOD" TIMESTAMP ,
  "ACTIVO" DECIMAL NOT NULL ,
  "DISPOSITIVO" VARCHAR(30) ,
  "TOKEN" VARCHAR(250)
);



--DROP SEQUENCE "APP_CONFIG_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."APP_CONFIG_SEQ" MINVALUE 1 MAXVALUE 9999999  INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."CAT_ESTATUS_DESCRIPCION_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."CAT_ESTATUS_DESCRIPCION_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_DET_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_DET_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_EMAIL_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_EMAIL_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_ROL_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_ROL_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."CAT_INCIDENCIA_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."MOVIMIENTOS_TICKET_WS_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."MOVIMIENTOS_TICKET_WS_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."MOVIMIENTOS_WS_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."MOVIMIENTOS_WS_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."ROLES_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."ROLES_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."TEMPORAL_USUARIOS_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."TEMPORAL_USUARIOS_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."TICKET_DET_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."TICKET_DET_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."TICKET_IMG_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."TICKET_IMG_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."TICKET_MSG_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."TICKET_MSG_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."TICKET_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."TICKET_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."TIPO_UNIDAD_ROL_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."TIPO_UNIDAD_ROL_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."TIPO_UNIDAD_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."TIPO_UNIDAD_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;

--DROP SEQUENCE "UGATMMOVILADMIN"."USUARIO_SEQ";
CREATE SEQUENCE "UGATMMOVILADMIN"."USUARIO_SEQ" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 CACHE 20;
